---
- name: Change creation process begins
  hosts: localhost
- import_playbook: change_creation_Test_yaml.yml
- name: Change creation process end
  hosts: localhost
  tasks:
    - debug: 
        msg: "change creation process completed successfully"
